---
title: "USP654: Data Analysis II"
subtitle: "Bivariate Regression"
author: "Liming Wang"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  xaringan::moon_reader:
    seal: yes
    nature:
      highlightStyle: github
---

```{r setup, include=F}
knitr::opts_chunk$set(message=FALSE, warning=F, echo=F)
options(width = 2000)
```

# Outline

- Why Regression Analysis?
- 

---

# Why Regression Analysis?

- Regression analysis allows scientists to quantify how the average of one variable systematically varies according to the levels of another variable;
- Comparing with hypothesis testing techinque we reviewed before, additional variables can be introduced into regression models to help to determine if a relationship is genuine or spurious;
- Regression models also allow scientists to examine the mechanisms that their theories and ideas suggest explain the association between a particular predictor variable and an outcome;
- Regression models can be used to examine how two predictors jointly associate with an outcome variable;
- Regression models can be used for predictions or scenario analysis.

---

# Why Regression Analysis - An Example

[Eng, Sothy. 2012. “Cambodian Early Adolescents’ Academic Achievement: The Role of Social Capital.” Journal of Early Adolescence 33(3): 378–403.](http://journals.sagepub.com/doi/pdf/10.1177/0272431612441069)
